project:
  type: website
  output-dir: docs

website:
  title: |
    Quarto 🤝 Julia
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Examples
        menu:
          - href: examples/article/index.qmd
            text: HTML Article
          - href: examples/revealjs/index.qmd
            text: Revealjs Presentation
          - href: examples/documenter/index.qmd
            text: "Working with `Documenter.jl`" 

format:
  julia-html:
    toc: true



